// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClm6Yvs_inJ_RisK355-NIkZTYJ1zOXPw',
    appId: '1:85257832115:web:135a02c47649559e2e92c6',
    messagingSenderId: '85257832115',
    projectId: 'maan-nataalam',
    authDomain: 'maan-nataalam.firebaseapp.com',
    storageBucket: 'maan-nataalam.firebasestorage.app',
    measurementId: 'G-5GE2CTL4GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtE98FVsvMpCF-TTCqIWRNiydT_48u3R4',
    appId: '1:85257832115:android:baa45f07602506f02e92c6',
    messagingSenderId: '85257832115',
    projectId: 'maan-nataalam',
    storageBucket: 'maan-nataalam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ8IG7m7o5nR5IH_owcrqxnpVM7NCCI5I',
    appId: '1:85257832115:ios:5f0a34f35cfe2b112e92c6',
    messagingSenderId: '85257832115',
    projectId: 'maan-nataalam',
    storageBucket: 'maan-nataalam.firebasestorage.app',
    iosBundleId: 'com.zuwad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ8IG7m7o5nR5IH_owcrqxnpVM7NCCI5I',
    appId: '1:85257832115:ios:5f0a34f35cfe2b112e92c6',
    messagingSenderId: '85257832115',
    projectId: 'maan-nataalam',
    storageBucket: 'maan-nataalam.firebasestorage.app',
    iosBundleId: 'com.zuwad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClm6Yvs_inJ_RisK355-NIkZTYJ1zOXPw',
    appId: '1:85257832115:web:5ba5b70502a0ab372e92c6',
    messagingSenderId: '85257832115',
    projectId: 'maan-nataalam',
    authDomain: 'maan-nataalam.firebaseapp.com',
    storageBucket: 'maan-nataalam.firebasestorage.app',
    measurementId: 'G-KBZ313L9NH',
  );
}
